/**
 * Shared C / C++ keyword sets for line-level syntax highlighting.
 * Preprocessor entries are matched as a single program token by the shared state machine.
 */

const CCPP_PREPROCESSOR_KEYWORDS = [
  "#define",
  "#elif",
  "#else",
  "#endif",
  "#error",
  "#if",
  "#ifdef",
  "#ifndef",
  "#include",
  "#line",
  "#pragma",
  "#undef",
] as const;

/** ISO C11 §6.4.1 keywords (including underscore forms). */
const C_LANGUAGE_KEYWORDS = [
  "_Alignas",
  "_Alignof",
  "_Atomic",
  "_Bool",
  "_Complex",
  "_Generic",
  "_Imaginary",
  "_Noreturn",
  "_Static_assert",
  "_Thread_local",
  "auto",
  "break",
  "case",
  "char",
  "const",
  "continue",
  "default",
  "do",
  "double",
  "else",
  "enum",
  "extern",
  "float",
  "for",
  "goto",
  "if",
  "inline",
  "int",
  "long",
  "register",
  "restrict",
  "return",
  "short",
  "signed",
  "sizeof",
  "static",
  "struct",
  "switch",
  "typedef",
  "union",
  "unsigned",
  "void",
  "volatile",
  "while",
] as const;

/**
 * C++23 keywords (ISO C++20 core + modules + C++23 additions). Alternative tokens (and, or, …) included.
 * Kept separate from C because several C forms (e.g. restrict, _Bool) are not C++ keywords.
 */
const CPP_LANGUAGE_KEYWORDS = [
  "alignas",
  "alignof",
  "and",
  "and_eq",
  "asm",
  "auto",
  "bitand",
  "bitor",
  "bool",
  "break",
  "case",
  "catch",
  "char",
  "char8_t",
  "char16_t",
  "char32_t",
  "class",
  "compl",
  "concept",
  "const",
  "const_cast",
  "consteval",
  "constexpr",
  "constinit",
  "continue",
  "co_await",
  "co_return",
  "co_yield",
  "decltype",
  "default",
  "delete",
  "do",
  "double",
  "dynamic_cast",
  "else",
  "enum",
  "explicit",
  "export",
  "extern",
  "false",
  "float",
  "for",
  "friend",
  "goto",
  "if",
  "import",
  "inline",
  "int",
  "long",
  "module",
  "mutable",
  "namespace",
  "new",
  "noexcept",
  "not",
  "not_eq",
  "nullptr",
  "operator",
  "or",
  "or_eq",
  "private",
  "protected",
  "public",
  "register",
  "reinterpret_cast",
  "requires",
  "return",
  "short",
  "signed",
  "sizeof",
  "static",
  "static_assert",
  "static_cast",
  "struct",
  "switch",
  "template",
  "this",
  "thread_local",
  "throw",
  "true",
  "try",
  "typedef",
  "typeid",
  "typename",
  "typeof",
  "typeof_unqual",
  "union",
  "unsigned",
  "using",
  "virtual",
  "void",
  "volatile",
  "wchar_t",
  "while",
  "xor",
  "xor_eq",
] as const;

/** Common <stdint.h> / <cstdint> typedefs — not language keywords; highlighted like keywords for readability. */
const CCPP_STDINT_ALIASES = [
  "int8_t",
  "int16_t",
  "int32_t",
  "int64_t",
  "int_fast8_t",
  "int_fast16_t",
  "int_fast32_t",
  "int_fast64_t",
  "int_least8_t",
  "int_least16_t",
  "int_least32_t",
  "int_least64_t",
  "intmax_t",
  "intptr_t",
  "uint8_t",
  "uint16_t",
  "uint32_t",
  "uint64_t",
  "uint_fast8_t",
  "uint_fast16_t",
  "uint_fast32_t",
  "uint_fast64_t",
  "uint_least8_t",
  "uint_least16_t",
  "uint_least32_t",
  "uint_least64_t",
  "uintmax_t",
  "uintptr_t",
] as const;

function keywordSet(...groups: readonly (readonly string[])[]): Set<string> {
  const out = new Set<string>();
  for (const g of groups) for (const k of g) out.add(k);
  return out;
}

export const C_KEYWORDS = keywordSet(C_LANGUAGE_KEYWORDS, CCPP_PREPROCESSOR_KEYWORDS, CCPP_STDINT_ALIASES);

export const CPP_KEYWORDS = keywordSet(CPP_LANGUAGE_KEYWORDS, CCPP_PREPROCESSOR_KEYWORDS, CCPP_STDINT_ALIASES);
